// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrFAodfORIBBY5ZIEyw70cqcDwacP8O6o',
    appId: '1:852531365399:web:e7c8a7ae49fa4b6e83be52',
    messagingSenderId: '852531365399',
    projectId: 'legalassist-ecdca',
    authDomain: 'legalassist-ecdca.firebaseapp.com',
    storageBucket: 'legalassist-ecdca.firebasestorage.app',
    measurementId: 'G-DYKM9KYQJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8LE2_Lyi4QZpszp7MDrMkXjj_FeNTzws',
    appId: '1:852531365399:android:6d0053ebf56257c083be52',
    messagingSenderId: '852531365399',
    projectId: 'legalassist-ecdca',
    storageBucket: 'legalassist-ecdca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdWO9m4dJO_HvkxiGDKwpXEipAjL5MBLA',
    appId: '1:852531365399:ios:58dca6bca5cb909983be52',
    messagingSenderId: '852531365399',
    projectId: 'legalassist-ecdca',
    storageBucket: 'legalassist-ecdca.firebasestorage.app',
    iosBundleId: 'com.example.legalAssist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdWO9m4dJO_HvkxiGDKwpXEipAjL5MBLA',
    appId: '1:852531365399:ios:58dca6bca5cb909983be52',
    messagingSenderId: '852531365399',
    projectId: 'legalassist-ecdca',
    storageBucket: 'legalassist-ecdca.firebasestorage.app',
    iosBundleId: 'com.example.legalAssist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrFAodfORIBBY5ZIEyw70cqcDwacP8O6o',
    appId: '1:852531365399:web:74c59cc0bddae3a983be52',
    messagingSenderId: '852531365399',
    projectId: 'legalassist-ecdca',
    authDomain: 'legalassist-ecdca.firebaseapp.com',
    storageBucket: 'legalassist-ecdca.firebasestorage.app',
    measurementId: 'G-SB5Y8YKHZZ',
  );
}
